### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Mullayam** [arnidan/simple-ts-express-decorators#58]
why it is not wrking

**Comment by arnidan** [comment]
Please, provide a more detailed description. Feel free to reopen the issue.

**Comment by Mullayam** [comment]
have a lokk please


![image](https://github.com/arnidan/simple-ts-express-decorators/assets/50077856/11907ca7-4a82-4fac-a8aa-4ec839bed4eb)
![image](https://github.com/arnidan/simple-ts-express-decorators/assets/50077856/e6e76af1-6698-4217-9ac3-56e7fe997a57)
